<?php

namespace Pipiou\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PipiPlaceEvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PipiPlaceEvaluationRepository extends EntityRepository
{
}
